LLM_COMMANDS = {
    "summarize": "SUM:",
    "rewrite": "RW:",
    "explain": "EXP:",
    "tone": "TONE:",
    "bullets": "BULLETS:",
    "title": "TITLE:",
    "tweet": "TWEET:",
    "email": "EMAIL:",
    "regex": "REGEX:",
    "docstring": "DOCSTRING:",
    "review": "REVIEW:",
    "gitcommit": "GITCOMMIT:",
    "meeting": "MEETING:",
    "todo": "TODO:",
    "eli5": "ELI5:",
    "haiku": "HAIKU:",
    "roast": "ROAST:",
    "fill": "FILL:",
    "trans": "TRANS:",
}
