TEXT_COMMANDS = {
    "translate": "TR:",
    "test": "TEST:",
    "fmt": "FMT:",
    "count": "COUNT:",
    "mock": "MOCK:",
    "b64": "B64:",
    "decode": "DECODE:",
    "hash": "HASH:",
    "redact": "REDACT:",
    "calc": "CALC:",
    "date": "DATE:",
    "escape": "ESCAPE:",
    "sanitize": "SANITIZE:",
    "password": "PASSWORD:",
    "clip": "CLIP:",
    "stack": "STACK:",
    "pop": "POP:",
    "repeat": "REPEAT:",
}
